#! /bin/sh

setxkbmap latam &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 
#bspc monitor -d I II III IV V 
#VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#### BSPWM COLORING ####
#
bspc config normal_border_color         "#51576d"
bspc config active_border_color         "#d5a4b5"
bspc config focused_border_color        "#d5a4b5"
bspc config presel_feedback_color       "#d5a4b5"
bspc config urgent_border_color         "#d5a4b5"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Thunar desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# POLYBAR
$HOME/.config/polybar/fail/launch.sh

# Wallpaper
feh --bg-fill ~/Wallpaper/fail.png &

# Picom
picom &
bspc config border_width 0
